import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ProjectMcpServerCreatedPayload as ContractsProjectMcpServerCreatedPayloadSchema,
  ProjectMcpServerRemovedPayload as ContractsProjectMcpServerRemovedPayloadSchema,
  ProjectMcpServerUpdatedPayload as ContractsProjectMcpServerUpdatedPayloadSchema,
  EnvironmentMcpDefinitionCreatedPayload as ContractsEnvironmentMcpDefinitionCreatedPayloadSchema,
  EnvironmentMcpDefinitionUpdatedPayload as ContractsEnvironmentMcpDefinitionUpdatedPayloadSchema,
  EnvironmentMcpDefinitionRemovedPayload as ContractsEnvironmentMcpDefinitionRemovedPayloadSchema,
  ProjectMcpDefinitionCreatedPayload as ContractsProjectMcpDefinitionCreatedPayloadSchema,
  ProjectMcpDefinitionUpdatedPayload as ContractsProjectMcpDefinitionUpdatedPayloadSchema,
  ProjectMcpDefinitionRemovedPayload as ContractsProjectMcpDefinitionRemovedPayloadSchema,
  ProjectMcpOverrideUpsertedPayload as ContractsProjectMcpOverrideUpsertedPayloadSchema,
  ProjectMcpOverrideRemovedPayload as ContractsProjectMcpOverrideRemovedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ThreadMcpCatalogInitializedPayload as ContractsThreadMcpCatalogInitializedPayloadSchema,
  ThreadMcpCatalogUpdatedPayload as ContractsThreadMcpCatalogUpdatedPayloadSchema,
  ThreadMcpCatalogResetPayload as ContractsThreadMcpCatalogResetPayloadSchema,
  ThreadMcpCatalogDisposedPayload as ContractsThreadMcpCatalogDisposedPayloadSchema,
  ThreadMcpCatalogAppliedPayload as ContractsThreadMcpCatalogAppliedPayloadSchema,
  ThreadMcpCatalogApplyFailedPayload as ContractsThreadMcpCatalogApplyFailedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const ProjectMcpServerCreatedPayload = ContractsProjectMcpServerCreatedPayloadSchema;
export const ProjectMcpServerUpdatedPayload = ContractsProjectMcpServerUpdatedPayloadSchema;
export const ProjectMcpServerRemovedPayload = ContractsProjectMcpServerRemovedPayloadSchema;
export const EnvironmentMcpDefinitionCreatedPayload =
  ContractsEnvironmentMcpDefinitionCreatedPayloadSchema;
export const EnvironmentMcpDefinitionUpdatedPayload =
  ContractsEnvironmentMcpDefinitionUpdatedPayloadSchema;
export const EnvironmentMcpDefinitionRemovedPayload =
  ContractsEnvironmentMcpDefinitionRemovedPayloadSchema;
export const ProjectMcpDefinitionCreatedPayload = ContractsProjectMcpDefinitionCreatedPayloadSchema;
export const ProjectMcpDefinitionUpdatedPayload = ContractsProjectMcpDefinitionUpdatedPayloadSchema;
export const ProjectMcpDefinitionRemovedPayload = ContractsProjectMcpDefinitionRemovedPayloadSchema;
export const ProjectMcpOverrideUpsertedPayload = ContractsProjectMcpOverrideUpsertedPayloadSchema;
export const ProjectMcpOverrideRemovedPayload = ContractsProjectMcpOverrideRemovedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
export const ThreadMcpCatalogInitializedPayload = ContractsThreadMcpCatalogInitializedPayloadSchema;
export const ThreadMcpCatalogUpdatedPayload = ContractsThreadMcpCatalogUpdatedPayloadSchema;
export const ThreadMcpCatalogResetPayload = ContractsThreadMcpCatalogResetPayloadSchema;
export const ThreadMcpCatalogDisposedPayload = ContractsThreadMcpCatalogDisposedPayloadSchema;
export const ThreadMcpCatalogAppliedPayload = ContractsThreadMcpCatalogAppliedPayloadSchema;
export const ThreadMcpCatalogApplyFailedPayload = ContractsThreadMcpCatalogApplyFailedPayloadSchema;
